//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivos
    {
        public Dispositivos()
        {
            this.Prestamos = new HashSet<Prestamos>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string TipoDispositivo { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string EstadoInventario { get; set; }
    
        public virtual ICollection<Prestamos> Prestamos { get; set; }
    }
}
