//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int ID { get; set; }
        public System.DateTime FechaPrestamos { get; set; }
        public int CodEstudiante { get; set; }
        public int CodDispositivo { get; set; }
        public System.TimeSpan HoraPrestamos { get; set; }
        public System.TimeSpan HoraEntrega { get; set; }
        public string Estado { get; set; }
    
        public virtual Dispositivos Dispositivos { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
