//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public int id { get; set; }
        public string isbn { get; set; }
        public string nombre { get; set; }
        public int ideditorial { get; set; }
        public int numeropaginas { get; set; }
        public int idcategoria { get; set; }
        public int idautor { get; set; }
    
        public virtual autores autores { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual editoriales editoriales { get; set; }
    }
}
