//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibreriaBDEntities : DbContext
    {
        public LibreriaBDEntities()
            : base("name=LibreriaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autores> autores { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<editoriales> editoriales { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
