//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacionjardin
    {
        public string niup { get; set; }
        public string nomjar { get; set; }
        public System.DateTime fecha_asig { get; set; }
    
        public virtual Datninos Datninos { get; set; }
        public virtual Regjardines Regjardines { get; set; }
    }
}
