//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datninos
    {
        public Datninos()
        {
            this.asignacionjardin = new HashSet<asignacionjardin>();
            this.regasistencia = new HashSet<regasistencia>();
            this.RegNotas = new HashSet<RegNotas>();
        }
    
        public string niup { get; set; }
        public string nomape { get; set; }
        public string tip_san { get; set; }
        public string ciu_nac { get; set; }
        public string ide_acu { get; set; }
        public System.DateTime fec_nac { get; set; }
        public string dir { get; set; }
        public string tel { get; set; }
        public string eps { get; set; }
    
        public virtual ICollection<asignacionjardin> asignacionjardin { get; set; }
        public virtual Dacudiente Dacudiente { get; set; }
        public virtual ICollection<regasistencia> regasistencia { get; set; }
        public virtual ICollection<RegNotas> RegNotas { get; set; }
    }
}
