//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regjardines
    {

        enum Estados
        {
            Aprobado, Entrámite, Negado
        }

        public Regjardines()
        {
            this.asignacionjardin = new HashSet<asignacionjardin>();

            

        }
    
        public string ced { get; set; }
        public string nom_jardin { get; set; }
        public string dire { get; set; }
        public string estado { get; set; }

            
        public virtual ICollection<asignacionjardin> asignacionjardin { get; set; }
        public virtual DatMadrecomunitaria DatMadrecomunitaria { get; set; }
    }
}
