//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegNotas
    {
        public string niup { get; set; }
        public string ano_escolar { get; set; }
        public string nivel { get; set; }
        public string nota { get; set; }
        public System.DateTime fec { get; set; }
        public string observaciones { get; set; }
    
        public virtual Datninos Datninos { get; set; }
    }
}
